#library("ClimClass")
library('kgc')
library(intrval)

#data = read.table("/ebio/abt6_projects9/pathodopsis_microbiomes/data/meta_data/Pathodopsis_site_metadata_20190808.txt", sep="\t", fill = TRUE, header = T)

persample = read.table("/ebio/abt6_projects9/pathodopsis_microbiomes/data/meta_data/v2_master_M_12_2019.txt", sep = "\t", header = T, na.strings = "NA")

#read.table("/ebio/abt6_projects9/pathodopsis_microbiomes/data/meta_data/v1_Master_Pathodopsis_M_2018-07-20.csv", sep=",", header = T)

persample = subset(persample, select = -c(Notes))

#persample = merge(persample, data, by="Site_ID")

missing = unique(persample$Site_ID[which(persample$Site_ID %ni% data$Site_ID)])
write.table(missing, "/ebio/abt6_projects9/pathodopsis_microbiomes/data/meta_data/missing_info.txt", quote = FALSE, row.names = FALSE, col.names = FALSE)
data = persample
data <- data.frame(data,
                   rndCoord.lon = RoundCoordinates(data$Long),
                   rndCoord.lat = RoundCoordinates(data$Lat))

data <- data.frame(data,ClimateZ=LookupCZ(data, res="course"))
#look up climate zone

write.table(data, "/ebio/abt6_projects9/pathodopsis_microbiomes/pathodopsis_git/data/Pathodopsis_site_metadata_20190808_CZ_course3.txt", quote = FALSE, row.names = FALSE, sep="\t")

#old version was generated by using the commented out data